### ISSUE TITLE
calibration of camera and 2D lidar 

### ISSUE THREAD

**Issue by woshicver** [TouchDeeper/BetaGo#7]
你好，我看你也研究过MegviiRobot/CamLaserCalibraTool，所以请教你一下，在源码中LaseCamCalCeres.cpp中57行，计算雅克比矩阵的时候 :   jaco_i.rightCols<3>() = planar_.head(3).transpose() * (-qcl.toRotationMatrix() * skewSymmetric(point_));  这边我有点不理解。

我的理解按照SLAM14讲中对se3求导的结果，雅克比矩阵不是应该这样计算：jaco_i.rightCols<3>() = planar_.head(3).transpose() *-skewSymmetric( qcl.toRotationMatrix() * point_+tcl);  为什么在源代码中没有把平移加上去？

**Comment by TouchDeeper** [comment]
平移是优化变量。当loss对旋转求导时， 平移当作常数，求导后平移为0。当loss对平移求导时，平移就被消去了。所以雅可比没有平移是正常的。

**Comment by woshicver** [comment]
你好，非常感谢你的回复，但是我还是不太理解你所说的，如果平移变量是常数，那么求导是0，既然平移是要优化的变量，为什么求导会是0。我梳理了一下我的推导过程，麻烦你帮我看一下问题在哪里，因为邮件里不太方便输入公式，我就截图了，附件里是对应的Word版本描述。
















在 2022-05-03 15:34:15，"庄庭达" ***@***.***> 写道：

平移是优化变量。当loss对旋转求导时， 平移当作常数，求导后平移为0。当loss对平移求导时，平移就被消去了。所以雅可比没有平移是正常的。

**Comment by TouchDeeper** [comment]
前提是“当loss对旋转求导时”。
我这好像看不到附件。

**Comment by woshicver** [comment]
感谢你的回复，我大概理清楚了源代码的思路，源代码是对旋转、平移分开求导，而且是右乘扰动，而我按照高翔老师的书，用的对旋转平移整体求导，左乘扰动。
















在 2022-05-04 14:26:38，"庄庭达" ***@***.***> 写道：

前提是“当loss对旋转求导时”。
我这好像看不到附件。

**Comment by woshicver** [comment]
你好，我在二维激光和相机标定时候，使用的是RPLIDAR，标定板采用棋盘格，显示的图像中标定板坐标轴比较准确，我想标定板位姿应该比较准确，但是最终相机和雷达的外参误差很大，感觉应该是激光雷达的数据导致的，我想问一下你遇到过这个问题么？
















在 2022-05-04 14:26:38，"庄庭达" ***@***.***> 写道：

前提是“当loss对旋转求导时”。
我这好像看不到附件。
